####################################################################################################
#                                 __  __   _______          _                                      #
#                                |  \/  | |__   __|        | |                                     #
#                                | \  / | ___| | ___   ___ | |___                                  #
#                                | |\/| |/ __| |/ _ \ / _ \| / __|                                 #
#                                | |  | | (__| | (_) | (_) | \__ \                                 #
#                                \_|  |_/\___\_/\___/ \___/|_|___/                                 #
#                              Developer's : Dreamin discord.gg/dreamin                            #
####################################################################################################

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
#>>       GENERAL CONFIGURATION      >>
#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

general:

  # Do not change this unless you know what you are doing.
  version: "0.0.1"

  # The prefix of the plugin
  prefix: "§8» §f"

  # The broadcast prefix of the plugin
  broadcast-prefix: "[§c§lMcTools§r] "

  #The API key https://ipgeolocation.io to obtain information to set the player's language according to their IP
  ip-api-key: ""

  #if activated the plugin takes into account that there is a resource pack, for customs/items guis and other, if deactivated it sets the guis by default
  resourcepack: false

  #Url of resource pack, set on joining the server
  resourcepack-url: ""

  #if activated, authorization to be able to connect with several accounts on the same IP, if deactivated authorization of one IP per account
  double-count: true

  remove-player: true

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
#>>         CHAT CONFIGURATION       >>
#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

#Liberate your server from the chat-reporting! Disable chat reporting with maximum compatibility.
chat:

  # Whether McTools should replace player (signed or unsigned) chat with
  # system messages. This is what makes chat not reportable.
  rewrite-chat: true

  # Whether McTools should claim to clients that secure chat is enforced.
  # With this set to true, the "Chat messages can't be verified" toast will not
  # be shown. This is, in default configurations, unrelated to allowing clients
  # not signing their messages join.
  claim-secure-chat-enforced: true

  # Whether to report the server as secure (disabling chat reporting) to the
  # NoChatReports client mod. This displays a green icon on the server list
  # screen and if enforce-secure-profiles is disabled the open chat screen
  # for users of the client-side mod.
  send-prevents-chat-reports-to-client: false


#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
#>>        VOICE CONFIGURATION       >>
#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

voice:

  #Don't forget to add the OpenAudioMc plugin if activated
  #true = enable voice mode, false = disable voice mode
  enable: false

  #wallMode if enabled, ensures that if a wall more than 2 blocks high is between two people, then the two cannot hear each other.
  #Don't forget to add the OpenAudioMc plugin if activated, and set enabled to true
  #true = enable wall mode, false = disable wall mode
  wall-mode: false

  #distanceMax defines the maximum distance between two people for wallMode.
  distance-max: 10

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
#>>        BUILD CONFIGURATION       >>
#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

build:

  #if activated, the plugin allows the player to use all the tools for the build (Management of armor stands and items)
  #the player must be op or have mctools.build permission to use this service
  enable: false

  armor-stand: false


#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
#>>      INTERFACE CONFIGURATION     >>
#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

interface:

  #if activated, the plugin start raycast for get if selected a object in interface
  raycast: false

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
#>>         DOOR CONFIGURATION       >>
#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

door:

  enable: false

  anim-open: "anim_open"

  anim-close: "anim_close"

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
#>>       INTERACT CONFIGURATION     >>
#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

interact:

  enable: false

  anim-interact: "anim_interact"

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
#>>        STAFF CONFIGURATION       >>
#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

staff:

  #if activated, the plugin allows the player to use all the tools for the staff
  #the player must be op or have mctools.staff permission to use this service
  enable: false

  #if activated, the plugin allows the player to use the cmd to freeze or unfreeze a player
  freeze: false

  # The broadcast prefix of the plugin for the staff
  broadcast-prefix: "[Staff] "

  chat:

    #if activated, the plugin allows the player to use chat between staff members
    enable: false

    #the prefix to put in front of the message
    #ex: !Hello staff
    prefix: "!"

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
#>>      LANGUAGE CONFIGURATION      >>
#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

#Default langauge on the server if
default-lang: fr_FR

#if enabled, set the player's language at first connection relative to their IP, if disabled set the player's language at first connection relative to the default language
lang-by-ip: false

#List of server languages that can be used
#Possibility to add more, but don't forget any information. Also put the default code in langCode
langs:
  fr_FR:
    display-name: "Français"
    lang-code: [fr_FR, fr_CA]
  en_GB:
    display-name: "English"
    code: [ en_GB, en_AU, en_CA, en_NZ, en_PT, en_UD, en_US ]

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
#>>       DATABASE INFORMATION       >>
#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

database:

  # How Plugin Should Store Data
  #  Database type. Currently, only supports MySQL and SQLite.
  #  Current options: SQLite or MYSQL
  type: SQLite

  # When using SQLite, the database will be stored in the plugin's data folder.
  #  What should the database file be named ?
  sqlLite:
    name: database

  # When using MySQL, the database will be stored on a MySQL server.
  mysql:
    host:
    port: 3306
    dbName: ""
    username: ""
    password: ""
    default-prefix: ""
