#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
#>>       PLUGIN CONFIGURATION       >>
#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
mcTools:
  prefix: "§8» §f" #player's msg
  broadcastprefix: "[§c§lMcTools§r] " #global's & console's msg

  ressourcepack: false

  defaultLang: fr_FR

  buildMode: false
  editMode: false
  defaultGui: false
  defaultItems: false
  voiceMode: false
  voiceWallMode: false #true = enable voice mode, false = disable voice mode
  voiceDistanceMax: 10 #max distance for voiceWallMode

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
#>>       DATABASE INFORMATION       >>
#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
sql:
  host:
  port: 3306
  dbName: ""
  username: ""
  password: ""
  defaultPrefix: ""
