#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
#>>       PLUGIN CONFIGURATION       >>
#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
mcTools:
  prefix: "§8» §f" #player's msg
  broadcastprefix: "[§c§lMcTools§r] " #global's & console's msg

  ipApiKey: ""

  ressourcepack: false

  defaultLang: fr_FR

  buildMode: false
  editMode: false
  defaultGui: false
  defaultItems: false
  voiceMode: false
  voiceWallMode: false #true = enable voice mode, false = disable voice mode
  voiceDistanceMax: 10 #max distance for voiceWallMode

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
#>>       DATABASE INFORMATION       >>
#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

# How Plugin Should Store Data
#  Database type. Currently, only supports MySQL and SQLite.
#  Current options: SQLite or MYSQL
databaseType: SQLite

# When using SQLite, the database will be stored in the plugin's data folder.
#  What should the database file be named?
sqlLite:
  name: database

mysql:
  host:
  port: 3306
  dbName: ""
  username: ""
  password: ""
  defaultPrefix: ""
