name: DreaminTools
version: '${version}'
main: fr.dreamin.dreamintools.McTools
api-version: '1.20'
commands:
  dt:
    description: McTools
    aliases: McTools
    permission: McTools.use
    permission-message: You don't have the permission to use this command.
  dvh:
    description: "dvh"
    aliases: ["dreaminvoicehote"]
  dv:
    description: "dv"
    aliases: ["dreaminvoice"]
  dvd:
    description: "dvd"
    aliases: ["dreaminvoicedev"]
  as:
    description: "as"
    aliases: [ "as" ]
  coal:
    description: "coal"
    aliases: [ "getcoal" ]
  getid:
    description: "getid"
    aliases: [ "getid" ]
  showvoice:
    description: "showvoice"
    aliases: [ "showvoice" ]
  tag:
    description: "tag"
    aliases: [ "tag" ]
  door:
    description: "door"
    aliases: [ "door" ]
  interact:
    description: "interact"
    aliases: [ "interact" ]